service: clean-shoes-service

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
       -  Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"


# functions:
#     graphQl:
#         handler: handler.get
#         events:
#             - http:
#                 path: graphql
#                 method: get
#                 cors: true

functions:
  query:
    handler: handler.handler
    events:
      - http:
          path: get
          method: get
